name: Run Pre Publish and Release stacks
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - id: prepublish
        uses: sundargs2000/stacks-pre-publish@debug
      - run: echo ${{ steps.prepublish.outputs.success }} 
      - run: if [ ${{ steps.prepublish.outputs.success }} == true ]; then echo "shiz equal"; fi
          
      - name: Create Release
        if: ${{ steps.prepublish.outputs.success == 'true' }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
